nome = input("Digite o seu nome: ").strip()
print(f'Seu nome em maiúculo é {nome.upper()}')
print(f'Seu nome e minúsculo é {nome.lower()}')
print(f'Seu nome tem {len(nome) - nome.count(' ')} letras')
print(f'Seu primeiro nome tem {nome.find(' ')} letras')
separa = nome.split()
print(separa)
